version: "3.8"
services:
    nginx-react:
      image: reactapp:latest
      container_name: myreactapp
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 80:80
      environment:
        NODE_ENV: production

        # ENV REACT_APP_USERPOOLID: ${REACT_APP_USERPOOLID}
        # ENV REACT_APP_CLIENTID: ${REACT_APP_CLIENTID}
        # ENV REACT_APP_APIURL: ${REACT_APP_APIURL}





    